"""empty message

Revision ID: 4786eacac3a3
Revises: 6e5c09ccb577
Create Date: 2020-04-18 22:21:32.789863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4786eacac3a3'
down_revision = '6e5c09ccb577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderRecord', sa.Column('bmid', sa.String(), nullable=False))
    op.create_foreign_key(None, 'OrderRecord', 'CarAllinfo', ['bmid'], ['bmid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'OrderRecord', type_='foreignkey')
    op.drop_column('OrderRecord', 'bmid')
    # ### end Alembic commands ###
