"""empty message

Revision ID: 61dcb3376333
Revises: 
Create Date: 2020-04-12 18:38:58.153773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dcb3376333'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CarAllinfo',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('UsedorNot', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('OrderRecord',
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('QueryRecord',
    sa.Column('qdid', sa.String(), nullable=False),
    sa.Column('qid', sa.String(), nullable=False),
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('qdid'),
    sa.UniqueConstraint('qdid')
    )
    op.create_table('RealtimeCarDetails',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('UsedorNot', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('RealtimeCarOrderRecord',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('oid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('ReservationRecord',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('reserved_time', sa.Integer(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('qdid', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('reserveStatus', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('ReservedCarStatus',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('carAmount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bmid'], ['CarAllinfo.bmid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReservedCarStatus')
    op.drop_table('ReservationRecord')
    op.drop_table('RealtimeCarOrderRecord')
    op.drop_table('RealtimeCarDetails')
    op.drop_table('QueryRecord')
    op.drop_table('OrderRecord')
    op.drop_table('CarAllinfo')
    # ### end Alembic commands ###
