"""empty message

Revision ID: 6e5c09ccb577
Revises: 61dcb3376333
Create Date: 2020-04-13 04:41:42.858032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5c09ccb577'
down_revision = '61dcb3376333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookingRecord',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('reserved_time', sa.Integer(), nullable=False),
    sa.Column('st', sa.Integer(), nullable=False),
    sa.Column('et', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bmid', sa.String(), nullable=False),
    sa.Column('qdid', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('reserveStatus', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.drop_table('ReservationRecord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReservationRecord',
    sa.Column('rid', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(), nullable=False),
    sa.Column('reserved_time', sa.INTEGER(), nullable=False),
    sa.Column('st', sa.INTEGER(), nullable=False),
    sa.Column('et', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('bmid', sa.VARCHAR(), nullable=False),
    sa.Column('qdid', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('reserveStatus', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.drop_table('BookingRecord')
    # ### end Alembic commands ###
